[package]
name = "minesweeper"
version = "0.1.0"
authors = ["Beepbop0 <hey.nikhil42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7.2", features = ["small_rng"]}